### ISSUE TITLE
备份失败，pdf文件夹没有内容

### ISSUE THREAD

**Issue by liurenjie520** [YaoZeyuan/stablog#115]
2022-08-02 15:15:02.692: [GenerateCustomer] 生成微博记录html列表 
2022-08-02 15:15:04.177: [GenerateCustomer] catch error 
2022-08-02 15:15:04.178: [GenerateCustomer] TypeError: mblog.pics is not iterable
    at Weibo.generateSingleWeiboElement (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\view\base.js:305:33)
    at Weibo.generateSingleItemElement (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\view\weibo.js:27:31)
    at Weibo.render (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\view\weibo.js:44:33)
    at C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:511:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:50:103)
    at _next (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:52:194)
    at C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:52:364
    at new Promise (<anonymous>)
    at C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:52:97
    at GenerateCustomer.asyncGenerateEbook (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:551:7)
    at C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:262:23
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:50:103)
    at _next (C:\Users\d\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:52:194) 
2022-08-02 15:15:04.179: [GenerateCustomer] command finish 
2022-08-02 15:15:04.179: [DispatchCommand] 生成电子书命令执行完毕 
2022-08-02 15:15:04.180: [DispatchCommand] 所有命令执行完毕 
2022-08-02 15:15:04.180: [DispatchCommand] command finish 
2022-08-02 15:15:04.180: 所有任务执行完毕, 打开电子书文件夹 =>   C:\Users\d\AppData\Local\Programs\stablog\resources\app\稳部落输出的电子书

**Comment by fengshuisir** [comment]
我也遇到了同样的问题

**Comment by YaoZeyuan** [comment]
我在3.3.7版本尝试修复了下, 看看是否恢复?

另外记得贴下测试失败的微博主页哈, 我这边要复现了问题才能修复

**Comment by liurenjie520** [comment]
https://weibo.com/u/6626748101 你试试

**Comment by fengshuisir** [comment]
3.3.7版本，可以正常备份。谢谢！

**Comment by fengshuisir** [comment]
> https://weibo.com/u/6626748101 你试试



> 我在3.3.7版本尝试修复了下, 看看是否恢复?
> 
> 另外记得贴下测试失败的微博主页哈, 我这边要复现了问题才能修复

3.3.7版本，可以正常备份。谢谢！

**Comment by fengshuisir** [comment]
> 我在3.3.7版本尝试修复了下, 看看是否恢复?
> 
> 另外记得贴下测试失败的微博主页哈, 我这边要复现了问题才能修复

3.3.7版本，可以正常备份。谢谢！
