### ISSUE TITLE
与上个issue不同的失败log

### ISSUE THREAD

**Issue by ALLDAYALLNiGHT** [YaoZeyuan/stablog#118]
上个issue指https://github.com/YaoZeyuan/stablog/issues/115#issue-1325400272，拷贝weibo.com/u/6047238248,RangeError开始不一样。更新3.3.7前有输出过pdf，因为没空间，只能将就测试下。这次准备好硬盘，但没能输出pdf。重装几次稳博客加IObit全家桶整体优化后也这样。

处理器	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
设备 ID	55EBB53E-24F6-4A09-BE7F-313FBEACC212
产品 ID	00331-10000-00001-AA968
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	为 10 触摸点提供触控支持

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎5/‎6
操作系统版本	22610.1
体验	Windows Feature Experience Pack 1000.22632.1000.0

2022-08-21 20:19:17.062: [GenerateCustomer] 将记录2022-08-21(第667/667项)下第1/1条微博渲染为图片
2022-08-21 20:19:17.181: [GenerateCustomer] 将页面2020-09-05(第1/667项)添加到pdf文件中
2022-08-21 20:19:17.181: [GenerateCustomer] 正在添加页面2020-09-05(第1/667项)下,第1/1条微博
2022-08-21 20:19:17.185: [GenerateCustomer] 将页面2020-09-06(第2/667项)添加到pdf文件中
2022-08-21 20:19:17.186: [GenerateCustomer] 正在添加页面2020-09-06(第2/667项)下,第1/2条微博
2022-08-21 20:19:17.196: [GenerateCustomer] 正在添加页面2020-09-06(第2/667项)下,第2/2条微博
2022-08-21 20:19:17.207: [GenerateCustomer] 将页面2020-09-07(第3/667项)添加到pdf文件中
2022-08-21 20:19:17.207: [GenerateCustomer] 正在添加页面2020-09-07(第3/667项)下,第1/1条微博
2022-08-21 20:19:17.214: [GenerateCustomer] 将页面2020-09-08(第4/667项)添加到pdf文件中
2022-08-21 20:19:17.214: [GenerateCustomer] 正在添加页面2020-09-08(第4/667项)下,第1/2条微博
2022-08-21 20:19:17.484: [GenerateCustomer] 正在添加页面2020-09-08(第4/667项)下,第2/2条微博
2022-08-21 20:19:17.486: [GenerateCustomer] 将页面2020-09-09(第5/667项)添加到pdf文件中
2022-08-21 20:19:17.487: [GenerateCustomer] 正在添加页面2020-09-09(第5/667项)下,第1/6条微博
2022-08-21 20:19:17.687: [GenerateCustomer] catch error
2022-08-21 20:19:17.687: [GenerateCustomer] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
at new NodeError (node:internal/errors:371:5)
at boundsError (node:internal/buffer:84:11)
at Buffer.readUInt16LE (node:internal/buffer:243:5)
at Object.validate (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\types\cur.js:7:20)
at finder (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\detector.js:26:55)
at Array.find (<anonymous>)
at Object.detector (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\detector.js:27:17)
at lookup (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\index.js:32:29)
at Function.imageSize (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\index.js:87:16)
at D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:1039:51
at Generator.next (<anonymous>)
at asyncGeneratorStep (D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:50:103)
at _next (D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:52:194)
2022-08-21 20:19:17.688: [GenerateCustomer] command finish
2022-08-21 20:19:17.688: [DispatchCommand] 生成电子书命令执行完毕
2022-08-21 20:19:17.688: [DispatchCommand] 所有命令执行完毕
2022-08-21 20:19:17.688: [DispatchCommand] command finish
2022-08-21 20:19:17.688: 所有任务执行完毕, 打开电子书文件夹 => D:\Program Files\stablog\resources\app\稳部落输出的电子书

**Comment by ALLDAYALLNiGHT** [comment]
pdf有些麻烦，我先转当HTML党试试

**Comment by ALLDAYALLNiGHT** [comment]
试了其他的，uid6929366128六百多条博，uid5419364872四千多条博。失败原因与上条相同。查到其他项目有出现类似的提问，也有标记 Closed as completed 的，但我没看懂，已经放弃了，仅仅顺手再发条。大大您不喜欢直接删除或关闭这个主题就行。

2022-08-23 12:16:58.408: [GenerateCustomer] 正在添加页面2022-08-01(第269/288项)下,第1/2条微博
2022-08-23 12:16:58.410: [GenerateCustomer] 正在添加页面2022-08-01(第269/288项)下,第2/2条微博
2022-08-23 12:16:58.609: [GenerateCustomer] catch error
2022-08-23 12:16:58.610: [GenerateCustomer] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
at new NodeError (node:internal/errors:371:5)
at boundsError (node:internal/buffer:84:11)
at Buffer.readUInt16LE (node:internal/buffer:243:5)
at Object.validate (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\types\cur.js:7:20)
at finder (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\detector.js:26:55)
at Array.find (<anonymous>)
at Object.detector (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\detector.js:27:17)
at lookup (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\index.js:32:29)
at Function.imageSize (D:\Program Files\stablog\resources\app\node_modules\image-size\dist\index.js:87:16)
at D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:1039:51
at Generator.next (<anonymous>)
at asyncGeneratorStep (D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:50:103)
at _next (D:\Program Files\stablog\resources\app\dist\command\generate\customer.js:52:194)
2022-08-23 12:16:58.610: [GenerateCustomer] command finish
2022-08-23 12:16:58.610: [DispatchCommand] 生成电子书命令执行完毕
2022-08-23 12:16:58.610: [DispatchCommand] 所有命令执行完毕
2022-08-23 12:16:58.610: [DispatchCommand] command finish
2022-08-23 12:16:58.611: 所有任务执行完毕, 打开电子书文件夹 => D:\Program Files\stablog\resources\app\稳部落输出的电子书

**Comment by ALLDAYALLNiGHT** [comment]
忘记夸夸大大啦！大大辛苦，神具万岁！

**Comment by ALLDAYALLNiGHT** [comment]
html真香，用什么pdf！多个步骤多些失败，还占大笔空间毫不怜惜我伤痕累累的硬盘🤣🤣
