### ISSUE TITLE
备份出错 ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by xax007** [YaoZeyuan/stablog#60]
备份出错了，生成目录什么都没有
```
2021-06-15 16:55:58.734: [GenerateCustomer] catch error 
2021-06-15 16:55:58.735: [GenerateCustomer] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
at boundsError (internal/buffer.js:71:11)
at Buffer.readUInt16LE (internal/buffer.js:230:5)
at Object.validate (/Applications/稳部落.app/Contents/Resources/app/node_modules/image-size/dist/types/cur.js:7:20)
at finder (/Applications/稳部落.app/Contents/Resources/app/node_modules/image-size/dist/detector.js:26:55)
at Array.find (<anonymous>)
at Object.detector (/Applications/稳部落.app/Contents/Resources/app/node_modules/image-size/dist/detector.js:27:17)
at lookup (/Applications/稳部落.app/Contents/Resources/app/node_modules/image-size/dist/index.js:32:29)
at Function.imageSize (/Applications/稳部落.app/Contents/Resources/app/node_modules/image-size/dist/index.js:87:16)
at /Applications/稳部落.app/Contents/Resources/app/dist/command/generate/customer.js:1034:51
at Generator.next (<anonymous>)
at asyncGeneratorStep (/Applications/稳部落.app/Contents/Resources/app/dist/command/generate/customer.js:50:103)
at _next (/Applications/稳部落.app/Contents/Resources/app/dist/command/generate/customer.js:52:194) 
2021-06-15 16:55:58.735: [GenerateCustomer] command finish 
2021-06-15 16:55:58.735: [DispatchCommand] 生成电子书命令执行完毕
```

系统 macOS 10.15   
GitHub 下载的最新版本

**Comment by YaoZeyuan** [comment]
提供下备份的url哈
